# Generated by Django 2.1.8 on 2019-05-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190530_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(error_messages={'unique': '电话号码重复!'}, max_length=20, unique=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='student',
            name='qq',
            field=models.CharField(error_messages={'unique': 'qq号码重复!'}, max_length=20, unique=True),
        ),
    ]
