# Generated by Django 2.1.8 on 2019-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0002_auto_20190517_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='qq',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
